-- Make Horses, Iron and Niter harvestable.
INSERT INTO Resource_Harvests
(ResourceType, YieldType, Amount, PrereqTech)
VALUES
    ('RESOURCE_HORSES', 'YIELD_GOLD', 20, 'TECH_ANIMAL_HUSBANDRY'),
    ('RESOURCE_HORSES', 'YIELD_PRODUCTION', 40, 'TECH_ANIMAL_HUSBANDRY'),
    ('RESOURCE_IRON', 'YIELD_GOLD', 20, 'TECH_MINING'),
    ('RESOURCE_IRON', 'YIELD_PRODUCTION', 40, 'TECH_MINING'),
    ('RESOURCE_NITER', 'YIELD_GOLD', 20, 'TECH_MILITARY_ENGINEERING'),
    ('RESOURCE_NITER', 'YIELD_PRODUCTION', 40, 'TECH_MILITARY_ENGINEERING');
