--==================
-- Kublai Khan
--==================
-- domestic trade routes get +1 food and +1 prod for each wonder in the destination city
INSERT INTO RequirementSets VALUES ('DISTRICT_IS_WORLD_WONDER_BBG', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements VALUES ('DISTRICT_IS_WORLD_WONDER_BBG', 'REQUIRES_DISTRICT_IS_WORLD_WONDER');
INSERT INTO Types (Type, Kind)
    VALUES
    ('MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER_BBG', 'KIND_MODIFIER');
INSERT INTO	DynamicModifiers (ModifierType,	CollectionType,	EffectType)
    VALUES
    ('MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER_BBG',	'COLLECTION_PLAYER_DISTRICTS', 'EFFECT_ATTACH_MODIFIER');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
    VALUES
    ('KK_DOMESTIC_TRADE_YIELD_FOOD_MODIFIER_ATTACH_BBG', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER_BBG', 'DISTRICT_IS_WORLD_WONDER_BBG'),
    ('KK_DOMESTIC_TRADE_YIELD_PROD_MODIFIER_ATTACH_BBG', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER_BBG', 'DISTRICT_IS_WORLD_WONDER_BBG'),
    ('DOMESTIC_TRADE_ROUTE_FOOD_PER_DEST_WONDER_BBG', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',	NULL),
	('DOMESTIC_TRADE_ROUTE_PROD_PER_DEST_WONDER_BBG', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', NULL),
    ('KK_FOREIGN_TRADE_YIELD_CULTURE_MODIFIER_ATTACH_BBG', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER_BBG', 'DISTRICT_IS_WORLD_WONDER_BBG'),
    ('KK_FOREIGN_TRADE_YIELD_SCIENCE_MODIFIER_ATTACH_BBG', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER_BBG', 'DISTRICT_IS_WORLD_WONDER_BBG'),
    ('FOREIGN_TRADE_ROUTE_CULTURE_PER_DEST_WONDER_BBG', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	NULL),
	('FOREIGN_TRADE_ROUTE_SCIENCE_PER_DEST_WONDER_BBG', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value)
    VALUES
    ('KK_DOMESTIC_TRADE_YIELD_FOOD_MODIFIER_ATTACH_BBG', 'ModifierId', 'DOMESTIC_TRADE_ROUTE_FOOD_PER_DEST_WONDER_BBG'),
    ('KK_DOMESTIC_TRADE_YIELD_PROD_MODIFIER_ATTACH_BBG', 'ModifierId', 'DOMESTIC_TRADE_ROUTE_PROD_PER_DEST_WONDER_BBG'),
    ('DOMESTIC_TRADE_ROUTE_FOOD_PER_DEST_WONDER_BBG', 'YieldType', 'YIELD_FOOD'),
    ('DOMESTIC_TRADE_ROUTE_FOOD_PER_DEST_WONDER_BBG', 'Amount', '1'),
    ('DOMESTIC_TRADE_ROUTE_PROD_PER_DEST_WONDER_BBG', 'YieldType', 'YIELD_PRODUCTION'),
    ('DOMESTIC_TRADE_ROUTE_PROD_PER_DEST_WONDER_BBG', 'Amount', '1'),
    ('KK_FOREIGN_TRADE_YIELD_CULTURE_MODIFIER_ATTACH_BBG', 'ModifierId', 'FOREIGN_TRADE_ROUTE_CULTURE_PER_DEST_WONDER_BBG'),
    ('KK_FOREIGN_TRADE_YIELD_SCIENCE_MODIFIER_ATTACH_BBG', 'ModifierId', 'FOREIGN_TRADE_ROUTE_SCIENCE_PER_DEST_WONDER_BBG'),
    ('FOREIGN_TRADE_ROUTE_CULTURE_PER_DEST_WONDER_BBG', 'YieldType', 'YIELD_CULTURE'),
    ('FOREIGN_TRADE_ROUTE_CULTURE_PER_DEST_WONDER_BBG', 'Amount', '1'),
    ('FOREIGN_TRADE_ROUTE_SCIENCE_PER_DEST_WONDER_BBG', 'YieldType', 'YIELD_SCIENCE'),
    ('FOREIGN_TRADE_ROUTE_SCIENCE_PER_DEST_WONDER_BBG', 'Amount', '1');
INSERT INTO TraitModifiers
    VALUES
    ('TRAIT_LEADER_KUBLAI', 'KK_DOMESTIC_TRADE_YIELD_FOOD_MODIFIER_ATTACH_BBG'),
    ('TRAIT_LEADER_KUBLAI', 'KK_DOMESTIC_TRADE_YIELD_PROD_MODIFIER_ATTACH_BBG'),
    ('TRAIT_LEADER_KUBLAI', 'KK_FOREIGN_TRADE_YIELD_CULTURE_MODIFIER_ATTACH_BBG'),
    ('TRAIT_LEADER_KUBLAI', 'KK_FOREIGN_TRADE_YIELD_SCIENCE_MODIFIER_ATTACH_BBG');


--==================
-- Vietnam
--==================
-- Unique district will now only get +1 culture from other adjacent district (from +2)
UPDATE District_Adjacencies SET YieldChangeId='District_Culture_Standard' WHERE DistrictType='DISTRICT_THANH';

-- Default movement point for unique unit is 2 (from 3)
UPDATE Units SET BaseMoves=2 WHERE UnitType='UNIT_VIETNAMESE_VOI_CHIEN';

--Combat strength on feature reduce to +2 (+4 in Vietnam territory)
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='TRIEU_FRIENDLY_COMBAT' AND Name='Amount';
UPDATE ModifierArguments SET Value='2' WHERE ModifierId='TRIEU_UNFRIENDLY_COMBAT' AND Name='Amount';
